# Mod
mod_id = devauth
mod_name = Dev Auth
mod_description = Authenticate with Microsoft while developing Minecraft mods
mod_version = 1.0.0+mc1.21.11
archives_base_name = devauth-fabric

# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# Find versions at: https://fabricmc.net/develop
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.3
loader_version=0.18.4
loom_version=1.14-SNAPSHOT

# Fabric API
fabric_version=0.140.2+1.21.11

# Dependencies
# Cloth Config: https://modrinth.com/mod/cloth-config/versions
cloth_config_version = 21.11.153

# Publish
maven_group = github.tbenassi.devauth